function(expect_error option value expected)
    execute_process(COMMAND "${SERVER}" "${option}" "${value}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 2)
    if(NOT result EQUAL 1 OR NOT error MATCHES "${expected}")
        message(FATAL_ERROR "Unexpected CLI result for ${option} ${value}: ${result}; ${output}; ${error}")
    endif()
endfunction()

execute_process(COMMAND "${SERVER}" --help RESULT_VARIABLE help_result OUTPUT_VARIABLE help)
if(NOT help_result EQUAL 0 OR NOT help MATCHES "Usage:")
    message(FATAL_ERROR "--help failed")
endif()
foreach(port IN ITEMS -1 65536 80junk abc 999999999999999999999999999)
    expect_error(--port "${port}" "Invalid port")
endforeach()
foreach(size IN ITEMS 0 -1 16777217 4096junk abc)
    expect_error(--buffer-size "${size}" "Invalid buffer size")
endforeach()
expect_error(--host "127.0.0.999" "Invalid endpoint")
expect_error(--unknown "x" "Unknown or incomplete argument")
